ad_id=AD12345
rotate_interval=28800  // 60 = Rotate every 60 seconds, mesures in seconds

imsi=123456789012345
rotate_interval=28800  // 60 = Rotate every 60 seconds, mesures in seconds

inzi=9876543210
rotate_interval=28800  // 60 = Rotate every 60 seconds, mesures in seconds
